MODEL = "gpt-4.1-mini" 

#USER_LOCATION = "Buenos Aires"

CITY_TO_IATA = {
    # América
    "buenos aires": "EZE",
    "la plata": "EZE",  
    "santiago": "SCL",
    "lima": "LIM",
    "bogotá": "BOG",
    "caracas": "CCS",
    "montevideo": "MVD",
    "asunción": "ASU",
    "la paz": "LPB",
    "sucre": "SRE",
    "brasilia": "BSB",
    "rio de janeiro": "GIG",
    "ciudad de méxico": "MEX",
    "mexico city": "MEX",
    "washington": "IAD",
    "washington dc": "IAD",
    "ottawa": "YOW",
    "la habana": "HAV",
    "panamá": "PTY",
    "panama city": "PTY",
    "san josé": "SJO",
    "san jose": "SJO",
    "kingston": "KIN",
    "santo domingo": "SDQ",

    # Europa
    "parís": "CDG",
    "paris": "CDG",
    "londres": "LHR",
    "london": "LHR",
    "madrid": "MAD",
    "roma": "FCO",
    "berlín": "BER",
    "berlin": "BER",
    "lisboa": "LIS",
    "viena": "VIE",
    "bruselas": "BRU",
    "amsterdam": "AMS",
    "praga": "PRG",
    "varsovia": "WAW",
    "budapest": "BUD",
    "atenas": "ATH",
    "dublín": "DUB",
    "dublin": "DUB",
    "oslo": "OSL",
    "estocolmo": "ARN",
    "helsinki": "HEL",
    "copenhague": "CPH",
    "reikiavik": "KEF",
    "moscú": "SVO",
    "moscow": "SVO",
    "kiev": "KBP",
    "kyiv": "KBP",
    "zagreb": "ZAG",
    "belgrado": "BEG",
    "sofía": "SOF",
    "sofia": "SOF",
    "bucharest": "OTP",
    "bucarest": "OTP",
    "bern": "ZRH",
    "ginebra": "GVA",

    # Asia
    "tokyo": "HND",
    "tokio": "HND",
    "pekin": "PEK",
    "pekín": "PEK",
    "beijing": "PEK",
    "seúl": "ICN",
    "seoul": "ICN",
    "bangkok": "BKK",
    "hanoi": "HAN",
    "manila": "MNL",
    "yakarta": "CGK",
    "jakarta": "CGK",
    "kuala lumpur": "KUL",
    "singapur": "SIN",
    "singapore": "SIN",
    "nueva delhi": "DEL",
    "new delhi": "DEL",
    "islamabad": "ISB",
    "teherán": "IKA",
    "tehran": "IKA",
    "bagdad": "BGW",
    "jerusalén": "TLV",
    "jerusalem": "TLV",
    "doha": "DOH",
    "abu dhabi": "AUH",
    "riad": "RUH",
    "riyadh": "RUH",
    "ankara": "ESB",
    "ulán bator": "ULN",
    "ulan bator": "ULN",

    # África
    "el cairo": "CAI",
    "cairo": "CAI",
    "pretoria": "JNB",
    "ciudad del cabo": "CPT",
    "cape town": "CPT",
    "nairobi": "NBO",
    "addis abeba": "ADD",
    "tunez": "TUN",
    "túnez": "TUN",
    "argel": "ALG",
    "rabat": "RBA",
    "dakar": "DSS",
    "accra": "ACC",
    "abuya": "ABV",
    "abuja": "ABV",
    "kampala": "EBB",
    "khartoum": "KRT",

    # Oceanía
    "canberra": "CBR",
    "sídney": "SYD",
    "sydney": "SYD",
    "wellington": "WLG",
    "suva": "SUV",
}

CITY_TO_IATA.update({
    "alabama": "MGM",
    "alaska": "JNU",
    "arizona": "PHX",
    "arkansas": "LIT",
    "california": "SMF",
    "colorado": "DEN",
    "connecticut": "BDL",
    "delaware": "ILG",
    "florida": "TLH",
    "georgia": "ATL",
    "hawaii": "HNL",
    "idaho": "BOI",
    "illinois": "SPI",
    "indiana": "IND",
    "iowa": "DSM",
    "kansas": "FOE",
    "kentucky": "LEX",
    "louisiana": "BTR",
    "maine": "AUG",
    "maryland": "BWI",
    "massachusetts": "BOS",
    "michigan": "LAN",
    "minnesota": "MSP",
    "mississippi": "JAN",
    "missouri": "COU",
    "montana": "HLN",
    "nebraska": "LNK",
    "nevada": "RNO",
    "new hampshire": "MHT",
    "new jersey": "TTN",
    "new mexico": "SAF",
    "new york": "ALB",
    "north carolina": "RDU",
    "north dakota": "BIS",
    "ohio": "CMH",
    "oklahoma": "OKC",
    "oregon": "PDX",
    "pennsylvania": "MDT",
    "rhode island": "PVD",
    "south carolina": "CAE",
    "south dakota": "PIR",
    "tennessee": "BNA",
    "texas": "AUS",
    "utah": "SLC",
    "vermont": "BTV",
    "virginia": "RIC",
    "washington": "SEA",
    "west virginia": "CRW",
    "wisconsin": "MSN",
    "wyoming": "CYS",
})